/*
 	Autor - Ewerton Maik
 	Data Criação - 30/07/2025
 	Objetivo - 	Este arquivo de script contêm os passos e orientações para habilitar
 				o modo de arquivo de log do oracle e habilitar também o recurso
 				do flashback.
 
 
	1 - Funções principais do UNDO:
		Rollback de transações: Permite desfazer alterações feitas por transações que não foram confirmadas (commit).
		Recuperação de dados: Em caso de falhas, o Oracle usa os dados de UNDO para restaurar o estado anterior.
		Controle de concorrência: Ajuda a manter versões anteriores dos dados para que outras sessões possam acessá-los sem conflito.
		Flashback: Recursos como Flashback Query usam UNDO para visualizar dados como estavam em um momento anterior.

	2 - Onde o UNDO é armazenado?
		Em tablespaces UNDO, que são áreas específicas do banco de dados dedicadas a esse tipo de dado.
		O conteúdo dessas tablespaces é gerenciado automaticamente pelo Oracle,
			especialmente em configurações com Automatic Undo Management (gerenciamento automático de UNDO).
*/


-- CONSULTANDO SE O BANCO DE DADOS ESTA COM O FLASHBACK HABILITADO
SELECT FLASHBACK_ON FROM V$DATABASE; -- FLASHBACK_ON

-- Ative o Flashback
ALTER DATABASE FLASHBACK ON;
ALTER DATABASE FLASHBACK OFF;

-- VERIFICANDO O PARÂMETRO DE undo_retention, QUE POR PADRÃO VEM 900 SEGUNDOS = 15 MINUTOS
SELECT name, value FROM v$parameter WHERE name LIKE '%undo%';

-- ALTERANDO O TEMPO DE RETENÇÃO DO UNDO_RETENTION
ALTER SYSTEM SET UNDO_RETENTION = 3600; -- por exemplo, 1 hora

-- Verifique se está em ARCHIVELOG
ARCHIVE LOG LIST;

-- Defina o tamanho do destino
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST_SIZE = 2G SCOPE=BOTH;

-- Configure o destino dos logs de recuperação
ALTER SYSTEM SET DB_RECOVERY_FILE_DEST = 'C:\oracle\db_recovery_file_dest' SCOPE=BOTH;

-- DEFININDO CAMINHO DE ONDE SERÁ REGISTRADO O LOG E O FORMATO
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=C:/oracle/archivelog' SCOPE=SPFILE;
ALTER SYSTEM SET LOG_ARCHIVE_FORMAT='log_%t_%s_%r.arc' SCOPE=SPFILE; -- parâmetro que define o modelo de nome dos arquivos de log arquivados.

-- ALTERANDO O BANCO DE NOARCHIVELOG PARA ARCHIVELOG
ALTER DATABASE ARCHIVELOG;

-- CONSULTANDO O MODO DO LOG
SELECT LOG_MODE FROM V$DATABASE;




-- 01 - CRIAÇÃO DA TABELA DE CADASTRO DE PRODUTOS
--DROP TABLE produtos;
SELECT * FROM produtos;

CREATE TABLE produtos (
    id 			NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome 		VARCHAR2(100),
    categoria 	VARCHAR2(50),
    preco 		NUMBER(10,2)
);

DELETE FROM produtos;
COMMIT

-- 02 - INSERT DE CADASTRO DE PRODUTOS

BEGIN
  INSERT INTO produtos (nome, categoria, preco) VALUES ('Mouse Óptico USB', 'Acessório', 59.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Teclado Mecânico RGB', 'Periférico', 249.99);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Monitor 24" LED Full HD', 'Display', 899.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Headset Gamer com Microfone', 'Áudio', 199.00);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('SSD NVMe 1TB', 'Armazenamento', 549.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Placa de Vídeo RTX 4060', 'Hardware', 1799.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Processador Intel i5 13ª Geração', 'Hardware', 1199.00);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Placa-mãe ATX Z690', 'Hardware', 999.00);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Gabinete Mid Tower com RGB', 'Gabinete', 349.00);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Fonte 600W 80 Plus Bronze', 'Energia', 299.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Webcam Full HD 1080p', 'Acessório', 189.00);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Impressora Multifuncional Wi-Fi', 'Periférico', 749.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Notebook 15.6” Core i7', 'Computador', 4399.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Estabilizador 1000VA', 'Energia', 219.90);
  DBMS_LOCK.SLEEP(5);

  INSERT INTO produtos (nome, categoria, preco) VALUES ('Cadeira Gamer Ergonômica', 'Mobília', 899.00);
  COMMIT;
END;


-- 03 - ATUALIZAÇÃO DE PREÇO PARA ALGUNS PRODUTOS

BEGIN
	UPDATE produtos SET preco = 69.90 	WHERE id = 1;  -- Mouse Óptico USB
	DBMS_LOCK.SLEEP(10);
	UPDATE produtos SET preco = 199.90 	WHERE id = 4; -- Headset Gamer
	DBMS_LOCK.SLEEP(10);
	UPDATE produtos SET preco = 1599.90 WHERE id = 6; -- Placa de Vídeo RTX 4060
	DBMS_LOCK.SLEEP(10);
	UPDATE produtos SET preco = 4499.90 WHERE id = 13; -- Notebook
	DBMS_LOCK.SLEEP(10);
	UPDATE produtos SET preco = 999.90 	WHERE id = 15; -- Cadeira Gamer
	DBMS_LOCK.SLEEP(10);
	COMMIT;
END;

-- 04 - EXCLUSÃO DE ALGUNS PRODUTOS

BEGIN
	DELETE FROM produtos WHERE id = 2;  -- Teclado Mecânico RGB
	DBMS_LOCK.SLEEP(10);
	DELETE FROM produtos WHERE id = 5;  -- SSD NVMe 1TB
	DBMS_LOCK.SLEEP(10);
	DELETE FROM produtos WHERE id = 8;  -- Placa-mãe ATX Z690
	DBMS_LOCK.SLEEP(10);
	DELETE FROM produtos WHERE id = 11; -- Webcam Full HD
	DBMS_LOCK.SLEEP(10);
	DELETE FROM produtos WHERE id = 14; -- Estabilizador 1000VA
	DBMS_LOCK.SLEEP(10);
	COMMIT;
END;


SELECT CURRENT_SCN FROM V$DATABASE;
SELECT * FROM produtos AS OF SCN 6134730;

-- 05 - Consulta usando Flashback

SELECT * FROM produtos AS OF TIMESTAMP TO_TIMESTAMP('2025-07-29 23:48:35', 'YYYY-MM-DD HH24:MI:SS');
SELECT * FROM produtos AS OF TIMESTAMP TO_TIMESTAMP('2025-07-29 23:51:00', 'YYYY-MM-DD HH24:MI:SS');
SELECT * FROM produtos AS OF TIMESTAMP (systimestamp - interval '6' minute);
SELECT systimestamp FROM dual;

SELECT * 
FROM produtos 
AS OF TIMESTAMP TO_TIMESTAMP('2025-07-29 22:45:00', 'YYYY-MM-DD HH24:MI:SS');

SELECT * FROM produtos AS OF TIMESTAMP TO_TIMESTAMP(SYSTIMESTAMP - INTERVAL '5' MINUTE);
SELECT * FROM produtos AS OF TIMESTAMP (SYSTIMESTAMP - INTERVAL '5' MINUTE);

